apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webtop
  namespace: webtop
spec:
  commonName: webtop.camsab.me
  secretName: webtop
  dnsNames:
    - webtop.camsab.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
