---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop
  labels:
    app: webtop
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: webtop
  template:
    metadata:
      labels:
        app: webtop
        name: webtop
    spec:
      nodeSelector:
        kubernetes.io/hostname: "rk1-4"
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: kubernetes.io/hostname
      #          operator: NotIn
      #          values:
      #          - rpi4-1
      containers:
      - name: webtop
        image: lscr.io/linuxserver/webtop:arch-xfce
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Australia/Sydney"
        - name: DRINODE
          value: "/dev/dri/renderD128"
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: dri
          mountPath: /dev/dri
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: dri
        hostPath:
          path: /dev/dri
