apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webtop
  namespace: webtop
spec:
  entryPoints:
    - websecure
  routes:
      - kind: Rule
        match: "Host(`webtop.camsab.me`)"
        priority: 10
        middlewares:
          - name: ak-outpost-authentik-embedded-outpost
            namespace: authentik
        services: 
          - name: webtop
            port: 3000
      # This part is only required for single-app setups
      - kind: Rule
        match: "Host(`webtop.camsab.me`) && PathPrefix(`/outpost.goauthentik.io/`)"
        priority: 15
        services:
          - name: ak-outpost-authentik-embedded-outpost
            namespace: authentik
            port: 9000
  tls:
    secretName: webtop