---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: webtop
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn-1-replicas
  resources:
    requests:
      storage: "10Gi"