apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'kube-prometheus-stack'
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 56.2.0
    helm:
      valueFiles:
      - $values/apps/kube-prometheus-stack/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-prometheus-stack
  project: default