apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry
  namespace: registry
spec:
  commonName: registry.camsab.me
  secretName: registry
  dnsNames:
    - registry.camsab.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
