apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry
  namespace: registry
spec:
  entryPoints:
    - web
  routes:
      - kind: Rule
        match: "Host(`registry.camsab.local`)"
        services: 
          - name: docker-registry-ui
            port: 80