apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-mirror
  labels:
    app: docker-registry-mirror
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      delete:
        enabled: true
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
    proxy:
      remoteurl: https://registry-1.docker.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcr-registry-mirror
  labels:
    app: gcr-registry-mirror
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      delete:
        enabled: true
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
    proxy:
      remoteurl: https://gcr.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ghcr-registry-mirror
  labels:
    app: ghcr-registry-mirror
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      delete:
        enabled: true
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
    proxy:
      remoteurl: https://ghcr.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-registry-mirror
  labels:
    app: k8s-registry-mirror
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      delete:
        enabled: true
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
    proxy:
      remoteurl: https://registry.k8s.io