apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry
    release: docker-registry-ui
  name: docker-registry
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: longhorn-1-replicas
  resources:
    requests:
      storage: 10Gi