apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: docker-registry-mirror
  name: docker-registry-mirror
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gcr-registry-mirror
  name: gcr-registry-mirror
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ghcr-registry-mirror
  name: ghcr-registry-mirror
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: k8s-registry-mirror
  name: k8s-registry-mirror
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi