apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry
    release: docker-registry-ui
  name: docker-registry
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi
