---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  labels:
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 600Gi
