---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  # Can't change it afterwards so for now I manually label the PVC directly... 
  #labels:
  #  recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Gi