---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  labels:
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2-replicas
  dataSource:
    name: photos
    kind: PersistentVolumeClaim
  resources:
    requests:
      storage: 600Gi
