apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik
spec:
  commonName: authentik.camsab.me
  secretName: authentik
  dnsNames:
    - authentik.camsab.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production