---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB7duAQF6ANUMCt4LOB0984yT8aa3jyCV/LcLxNWP+nxRLLkZm74rgNJedzMwgr/kR1RT2DqAe1DMb7XGvmSVV0/5fxZ1NJ7Bpi3rVsTlbjnsHbPLsuBeZcMZpkhPG+O38I3eV6KsQ8fU9kqgt7FqpGUA2j3I/O+rXrKzlIqWbvsUjlGB1uiVZ7VO6XaTVsWxrH6wUuHMVc4LA8fq9HmEL4/ipwOm7hnvY+RXC1Z64sCyMqgF/DhRSmu3VrvH0A8jCDnD2ON8UTWDFLOhrLg7aLHGV7NE6K38tEhjULSw/uNqVBcoqWLsQ6u/dCFlq7RY9MAqW51KvwyqxZNQv/tbOnxw+SYlfrbeyVijj2mFRlkPa+0sPQhJFrJ34KjjLAlp1OEoDA7v5DEFsS6HBIkSnw/vrSXlDPK1koVR4arHct0Z0p8cty7ZsBH94Jb5NTL9Lys5GwgM6ohV6UELAilIDi9Qmqeen3+4bLsBx0wdx9Hl46SjJoOdUgg5TEO/LqzJKNZpNQc4k+flD5Mu8dAhtTQ79FBvFiKBtET1a2bRgsgqlkTtOKtFTjCzHAm3NNzqaBKTTRGAAPhpmApAjQEqUT1iRPk1W4IxRPqbqR1hBCnC3YZjh6CPxKc+Hhv+ecCu53oGU8eB3VqHRss+p4B68blYRqxfACkdD6XEL5VysDIIvIU1HjHtOjask3eqQEACzXl6FCdVhzrNaZA8bEoJ7vFX72wkPO349CL9S4QJ8+fDDDHZOBoIev
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
