---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDbpooh3u/F+PSssDecQSDLKoZb7aAAgetBHlY6AXA+gEBRWqsBZ4GcUDTiOjkIyL/knk7IRQu8cjSGF6ruv/qDFkTDvT6QohQOgXEPX5lTi7BKvEdY+NJPKjwHMkyWHa6gyIafIVLdANmJBE9/UhidUhfRMNIGltooErjcs2X1LlzQ3vsIAcGwRIlYRwLDay5DCuyDy+HMSzunaAGQRXYQr7wCYuxgQieo1a3hkjizZL53RMHyMWB/PS2NF/2l+UejYv5kpjztSsn5NAG5UynRXfAUOqZijcDEuFgkDLirj/VXJtnyHMw0yek8eZrirObG+iL3SDkNZqMIzqmb8soj58KLWwQs05rYg4ntAZHdMmRwjuIl69CAa5VW4zguzPdgtv/7B1pYU4YfhVf/SESyrSKinhzEQIvb9TKic/eanN+U/cNwVmGvSA9F/dzVlgXuQYE250CEz8TeNjOmvazjLTcdqqJ9flBTyoOoRpi3CabqISsHiCrlsG0inIkLS7pPpchUOX0VGlIBMcVAcpTZGysb26HzFpnRiGoAjHci8kWPmhPAz5ySWyqHcqPGvb/Tf5+hgAbg/LgFpWhgf73JD3gyVQdEiiwnTBMyW8fS4RDmG6CIngfEv/bi+EMMyy5JUEOKniSDYXngBDKaPk4xI7wKWXdKDrik2pjcekFPhI2tl/tLYTtNwI+v4Kf+Vappn5jHqczuZz+xmxlaMoyE5w8xPH1e+FQwjaQIbz1iH3dSAq8gYIVKQajimjcoJkDw1H89/Ue2fA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
