---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC7OvpJW0SfVCk9zuKJRgOVSJnpSPBvpXJZEjGfliLLhqe7p+G7+0DmWuLkBroxur/Y8uyRDUSq8PZDDMaB7Xo2ZvFW1uFsYATDsG8lRsRULmUQDvoKbHKJYRXfZ/mmXMfeGfQfBGd/yCeHyBQsLjXHIXZ0BUtjn4PrCZ/RU/AMHg362RuyxcM2tMAS0YJEZGSi0VaPihbeIVcGQBX+rYFzhMqPG8d6cggWETWVvm2w0Lxl4Bf0wd6x4WkHB329aVoTNx3zaZ3H996bfc3/P1Fu3bBj8dc7szO5ZZrm/R0rM4H2hWmOtLG6FYHB6ZMlG8lqlmHfiL4l2dCYyoCnK6gMqk/ni6Q8Eaa8vVfjMbD72meL8JRPuRvldDw41P5sWJ14J7hgVcUjQ6oXWzUHGu927ViGqAt5g8BGCwTX/hbitdr2UBphalfoalDJOGELwtkxluaSfhREXRIMSJnnjgRpipiPld6yP33s7lC1td+4Iw13LwlJKHkcfQqhshlax604+he5x9kawyrMAV1uG2PmkxzPmpoiTxpfv9wpCYpQtzaMIvMtzOSZGhetM+nqqMMPqZSN1jvqHae0DhoySzdS2EeYDYeZF5XYFPTJ14dBgYbDdKh6abxyO3MGd9Zu1s6jka6lssCnqQjZJzZuDqRZCuKKN5XNttxnEVnDiw+Xi5PTdABgukTyH3cgBR0riObXZLgjAdOAcSZu2p8naDUlJ0gnrVUMhfxbxcdatOdL54HKzoCSCN5g
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
