---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAlOOzdC1V25oqZi/uq5VfGmo0URLBYeBtZzFKsKHaxXVVoJC+eRy6ad5unfRGeiIqtnyV19mlj/2ZyRxV0T+3lsGZ7Qpu4xV0GPxZ+9UaVqrtTpoWAdIJzqDomuP9TgYcE+Opr6UfdkfoREDSMKuiYEyc5qoQhxkxThw4dsm57S+qk9vUGIDwrzMCAPC/u+eQa86FoGOm21wxr+ve07OjqLJzN2rORdd4TpMDUIGsgeiK6kMNT2Beh5Jy7wkoHZ6hDnWhZACVBN9YjI/JjJGi0p7wdxLib2XHlJUzPBkaA2iWV/HcyNrLryK5Ns8+sfrONxVBLWNrgBWLARn8TJBl2gasF7c07mM3YWTZ8HTBnGcaxcYhwZlJvnq56dRBoJtO2n9pheaGl5vpbawo0gawndJXkPZzsmJoQHonRgzGit3vMspgKzhglVbkyANAOug7DntmDuAh+xsYuZYfvXRDR5s/hu9N8DSrjpU7ulTwn2wcsPqXlSV0n8y50FHi6XtuJuN5RmYmBj46uE0Vf0VYur363/wjBFBFMFBoS0kGnLWWbEROnYQuH7kWJzjL16A2uYOVw/ixiE+VXtJuwBdnFvub8GCtcyibIAweuCjT15Y/ydbWn9nnwYusmmdqJzBySj20qnvQiXj6DNtzZw+SjSEfx763sPJP2qq4LmHJ5JvOsy6nu1/N/WzHqMpbCgF/YOY+pDQCCeAiPD5MTT14niBPM8OLfXZCeuU0pqntxGQXPJr4SFEBn
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
