---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgDJecr7BntupInrtrII1WWsYu9bvjUC4m16X6l2QzPq4tDN9gl4OhWO/CTcvTuWngqZU6+PNAAYAMAB+C/nNq2ssqWzjvO/7/gX1xv32o073PyqyDlLAbh34BwaiOOXskLnF5R1Y792AvcUsb5YXRiz2Fm9i7+rNNHrHay1PvNbPCBIHCCbudX9frEo8u7WweIB0/btImCjZbL8cFPqqPJ8MlrleRYCC4Ighyo7b17TTb8fVyUQKm6y2eyFMmuosrsPj8GJNvbbm1AkAuu4fQV4Zy+fv+jk8HngnhhvRksV5hwxppL8+E/EcWLxgoxd9owgZJa0fupEP5NinnDyAEI8woVWFvsWvXHi4d5Pf7hnxgMWKCOhzK5d6SGWu0Kyp0dmuzbm8eXZbkehMkTbRXC8z6j0v5ho8xtr2QI4kgOc8OoFUNugcnzbIgQpVBc9ZeBG6eVqrhGNB3sa6eSvGsau8AvO0ffdUSSQ/ETAKbVTHJjRWONJE9vRRzPquAgpold2okYzS2ZfQ0pWd7O66I255U8VEayMx6FJJXx9Pn5OO4rt6HWCrLNJnKatzFh3iixy1ji9Y5bL4b4H5r4hqT/prLQHkcHElTCKraAjID58nqL7tiotgG834wrXEeNbsP9bL4APP0pUcXRR5XSq5fKkbVRt+n8xfgHcnlkDAAs+r4acFNemtLxNe6rq+4EeGM/KuvrAU51cTQhR38Nmr0Ii6oPYEgFX/jwgzwvNG3hrsZo3LLSomCvd
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
