apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  commonName: jellyfin.camsab.me
  secretName: jellyfin
  dnsNames:
    - jellyfin.camsab.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging