---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        name: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.9.10
        imagePullPolicy: Always
        volumeMounts:
        - name: media
          mountPath: "/media"
        - name: config
          mountPath: "/config"
        - name: cache
          mountPath: "/cache"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-nfs
      - name: config
        persistentVolumeClaim:
          claimName: config-v2
      - name: cache
        persistentVolumeClaim:
          claimName: cache-v2
