---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        name: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        imagePullPolicy: Always
        volumeMounts:
        - name: media
          mountPath: "/media"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: cache
        persistentVolumeClaim:
          claimName: cache
