---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    type: l2
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  ports:
    - port: 8096
      targetPort: 8096
      name: jellyfin