apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'cert-manager'
spec:
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: v1.14.2
    helm:
      valueFiles:
      - $values/apps/cert-manager/values.yaml
  - repoURL: https://github.com/camrossi/home-cluster
    path: apps/cert-manager/extra
    targetRevision: main
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  project: default