apiVersion: "openebs.io/v1beta1"
kind: DiskPool
metadata:
  name: rk1-1
  namespace: mayastor
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  node: rk1-1
  disks: /dev/nvme0n1
---
apiVersion: "openebs.io/v1beta1"
kind: DiskPool
metadata:
  name: rk1-2
  namespace: mayastor
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  node: rk1-1
  disks: /dev/nvme0n1
---
apiVersion: "openebs.io/v1beta1"
kind: DiskPool
metadata:
  name: rk1-3
  namespace: mayastor
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  node: rk1-1
  disks: /dev/nvme0n1