apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "1"
provisioner: io.openebs.csi-mayastor
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-2
  annotations:
    argocd.argoproj.io/sync-wave: "1"
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "2"
provisioner: io.openebs.csi-mayastor