router bgp 65000
 bgp router-id 192.168.0.1
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 192.168.0.3 remote-as 65001
 neighbor 192.168.0.4 remote-as 65001
 neighbor 192.168.0.5 remote-as 65001
 neighbor 192.168.0.8 remote-as 65001
 neighbor 192.168.0.6 remote-as 65001
 neighbor 192.168.0.9 remote-as 65001
 neighbor 192.168.0.7 remote-as 65001
 neighbor 192.168.0.10 remote-as 65001
 !
 address-family ipv4 unicast
  neighbor 192.168.0.3 next-hop-self
  neighbor 192.168.0.4 next-hop-self
  neighbor 192.168.0.5 next-hop-self
  neighbor 192.168.0.8 next-hop-self
  neighbor 192.168.0.6 next-hop-self
  neighbor 192.168.0.9 next-hop-self
  neighbor 192.168.0.7 next-hop-self
  neighbor 192.168.0.10 next-hop-self
  maximum-paths 16
 exit-address-family
exit
!
end