apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spliit
  namespace: spliit
spec:
  commonName: spliit.camsab.me
  secretName: spliit
  dnsNames:
    - spliit.camsab.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
