apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  type: ClusterIP
  selector:
    name: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 30007  