---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik
  namespace: authentik
spec:
  encryptedData:
    postgres_password: AgBrLMtPGqt5AyH5n8hUHgXzqjfg1LvO8mmTHlCFxeyx/40dL7rgou0WwEw8Qj2f9cJ9hg/rkGdNHvmt5V0VCRb/woZe9rvPHWdSwvfp8Dg47iugza+H05xrMlarGNxXdPLCn/3MvUDjR5fwYdWeC22n/5oqlww7NJU6UuKCVfwhKTrF9lPcX1XPqvbfiRW1UrcQgj8g8k5P3I6Fdd/S7ujBqC0ehIOI8XWYHfCzZ+QlsRfe8uIG6hPG/oCsP+URllGjflYGfLOIIY0sfyBcO4N0S6+8Q1jQlrvcD6E2EmTS3b1JXVcsnwRiV/HIzdZS3U5yABkP6/sdkp3jUqYF3/VPx/C7N6fbtOZUKmmkMFGy2gr4+B4RCgM4fGDzxlz+NEl+TDcL7PcMu7a0qozFAeYDswg8mboFf6XHGLU3SVAYmGCCb2knmh+GDY7tNOd6Nz0iQw6SSVsDswiI8BkVUMuIjVt+mm25IYFkZ137nezy/FPkgGio/+PRh9P3K1T1WLqxJ0pluN8C07lqucK9pQk9BrbaXX4D5rQGjsWCJiNBvLLKXc3Ovkzj9YGFNNcaVH/Kk7MCk5xLYpNPbC0G+/smoQoWKE1kRLND9Wsl606TCZ5Zg8Eq8taA7QTEsagB8npNZ3eURV2c1BO9SrH0kLbJoJj424Xl6x4tDfkYyKBntLbtRw+KNhQHamsXauCi0dRJCZjUBv35laFDwbp+cAPL3GfFXed9ICkIYWBADTv+716OU1JRg184lSKly0oBUSguNA==
    secret_key: AgABW8TDXitN5KQ5Lucj4KDowWsjzmK7/FhJuHW82jwXzRdLkOz7sOEEYA09647X5MqlmWY/QUdanHUfKHT27dvb1q3/1b9qtvGAYgkd2rSigVtxH/LR/YSlg8ucf5qMqqCocVJ6o6gok84Z7qjWXr9PdHEMAoHIe3JgXFu0jdYYg9hpHKO8xiJikwRaDlGCLXq/Yl5ARhusssBOe1Dfd1U9dzFSBU3Eqhf/a/KaW6iSRYauSjQhMbcjsSrUIdFDcDHg82AX44H8IUyCbCa93xBRKa68/qT8vQ2O34SXKRuyUuEo3RqUamcJ+MIIYpRsXmxEawW5YBMyFpg8i6/l+Z7x/F7ktZ/vSWGe7uuG6PLI/npj3N4LhYnZg2nJciBAFbp0KuS/UnvloQCQBTxogrI9MKirF4+5wqE6eqhA9AV9NHfaPxmb6aQfs0EAagFSvrCQ3wJamgoo/oQMhAVB3Yet22Tr3FwLxFzFvrrdxNiaMRT0JIoXJJtq22B7izGlVH4l/zry5IAi/vWusm989J3/u13usZmjFA+ozjbDyFEy4S5rszT31mJVbeSigBogHkqSBZPr/8iFpxKOpdZnqEimfWP3vwoLQWS/IJ5RrLhCZYUf+G92h4pexxAx8bn2VvuDvmaUjll/SZXsecHwm/QrwgaxR6JzOV3D8KuHIFAvff3W9MYJ2b3OyLVAVI6lQAID0BqJtqQ4RcDkhL7zQ+Zcm8I8d4wRGHAe3laUejmjUg72g7wRhtuSCM8XaezVGTyl9g==
  template:
    metadata:
      creationTimestamp: null
      name: authentik
      namespace: authentik
    type: Opaque
