---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-creds
  namespace: authentik
spec:
  encryptedData:
    postgres_password: AgB9CFRVXBbus/3wyDCMHaH+T8gYC2IgyvvnE32miPOaEQrhxqEoQpmOyF8ev21oz63ckzn4BpK4E5B+MLA/BKHaf9lhcVzd4QEUB9v3KbgxpzsgWxli4p5AMxH9HKA2cZ7tFLdwMkx2XHNhi/TtoJvCE3BtYnSnpNW/kMZYcB/rjcC7PW5sXQFD+zx1knOE0fNV2Wy4lNLyHiOyV8xQWQwKlD0kox+65Kh3k0KFAgi5ovTXr2mcWhL/yFDpS9xIjJsT9aBDsc+Tl7k6+3UF+EwGUTRcmhJKRB83aYBe3KI85EcpvgUV9Qn/8hrV4uKlALJT911U2dr3/7NXw7ihgHIUTyqlhJ1AfS+s0RpS/RBBQ0AiODSP34DLYCEKuHo2qul5GA1gt8T4pvhjDLwaJw14nZnEtWahmVwXux704gJRCsRzGmpO7R4X89oA/iHGdPE0NrlZVpB1Yt0y3pwBsMl0lZid4E8wnXMka/bTXcVFEnN1jzMhqMUp/B6c8TyXi7tB447cm8BujdbhCQ3DACvNAG/WT8NGkB/lt7SKaDp9A9jkJ+7f70euJWD/jAOc3DE8VxfFE+X9pfiPMRTRSEq/1x8K12XDWEhguYXDmqn3obddODTlLDrEC3KGXwENGviBOywjHRD4w5h2yCkYNmOVD22fhnDduJUnGDAtGquh8bQnTAmPF0ySAWDWQE5kfUOl84l3iQeJhFSqCVOOFEhVVK+/bT9+hu26BGLPY9beu3zZ/Ha5H574Cd8zU4O6rU4Ajg==
    secret_key: AgB/4NS2f6mky4Rbv10T4zWix1UwCyEeoEjB1VHMH5zaDEVRcicvZ8vc0yyHomUs3KDTNlGIhm4jSBXC00i+ctVbu36hm9NU0LhN1402BW64GUTAsgaV2Vs8Ak6+bTgEdh+MAj+J3zWUQ6CHCi84XkEiF0OjfSwtqXKoVwaJZbgjpWktk1dFj+FNuYmK5oRuZxBCHDGu/eTRzgL1Rzz6jS+LrieiaA5njSTxS3PeE3iG51SzMpwQm8rRnTZXMxj1OWoh5wSlgFdUwgO9mWcozznlnNWWKvulMk664+LMuhkWE2Kp5bGNcLA2bx4C1ykrX/4+r/u/RkS0whEOsOOxvlBvv68DsIefS6DaIgn9j60Kn8Bk/QmpW3ETXgBKl+sEc13EoVv7TA7oTyM72nIdDDp1+YalU0YUhx69ZRzRZuM0uVisQ6IHE08VaBN+TX4vsqxAwRKfhc9bxLooqTteZj59ZOU6C45ZNc1LzwJqP0h/sjl/8G9Rb2Ct7JhRJupMPev3bsffxsGcLqXGNyN+FDXBezIFzO5Wb6/YgZFlhVvoExmyuMoSVeUQXxX/Ua4p9ZRENpT1R1+ZuybkyeEC4N5JFs30namG7mTBLZ1kTWpyHBYwJTfz/jKb/fObiMcKvKWXCak1O0AqV93+XUv8IFbo2nixOtZMnKXFcnwGZn3RURIfNvIEM1NNtcSgyUBMdoF1MdVnNfcgC/qAp9CHF63I5gOVnlBzWzgjWRAoUmQlNpxxnK5YjYrmS3hKs+VConIcWA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-creds
      namespace: authentik
    type: Opaque
