apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'trilium'
spec:
  sources:
  - repoURL: 'https://triliumnext.github.io/helm-charts'
    chart: trilium
    targetRevision: 1.3.0
    helm:
      valueFiles:
      - $values/apps/trilium/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  - repoURL: https://github.com/camrossi/home-cluster
    path: apps/karakeep/extra
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: trilium
  project: default