controllers:
  main:
    containers:
      trilium:
        image:
          repository: triliumnext/notes
          tag: v0.98.1
          pullPolicy: IfNotPresent
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    size: 20Gi
    retain: true
    accessMode: ReadWriteOnce
    storageClass: longhorn-2-replicas
route:
  main:
    kind: HTTPRoute
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: http-gateway
        namespace: kube-system
    hostnames: 
      - trilium.camsab.me
    rules:
     - backendRefs:
        - name: test
          port: 80
