controllers:
  main:
    containers:
      trilium:
        image:
          repository: triliumnext/trilium
          tag: v0.98.1
          pullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: trilium-config
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: trilium

route:
  main:
    kind: HTTPRoute
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: https-gateway
        namespace: kube-system
    hostnames: 
      - trilium.camsab.me
    rules:
     - backendRefs:
        - name: trilium
          port: 8080