controllers:
  main:
    containers:
      trilium:
        image:
          repository: triliumnext/trilium
          tag: v0.98.1
          pullPolicy: IfNotPresent
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: trilium

route:
  main:
    kind: HTTPRoute
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: http-gateway
        namespace: kube-system
    hostnames: 
      - trilium.camsab.me
    rules:
     - backendRefs:
        - name: trilium
          port: 8080
