apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'authentik'
spec:
  sources:
  - repoURL: 'https://charts.goauthentik.io'
    chart: authentik
    targetRevision: '2024.4.2'
    helm:
      valueFiles:
      - $values/apps/authentik/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  - repoURL: https://github.com/camrossi/home-cluster
    path: apps/authentik/extras
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: authentik
  project: default