authentik:
    secret_key: file:///authentik-creds/secret_key
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: file:///authentik-creds/postgres_password
email:
    # -- SMTP Server emails are sent from, fully optional
    host: "smtp.gmail.com"
    port: 587
    # -- SMTP credentials, when left empty, no authentication will be done
    username: file:///authentik-creds/gmail_app_pass
    # -- SMTP credentials, when left empty, no authentication will be done
    password: file:///authentik-creds/gmail_app_pass
    # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_tls: true
    # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_ssl: false
    # -- Connection timeout
    timeout: 30
    # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
    from: "authentik@camsab.me"
ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: traefik
    enabled: true
    hosts:
        # Specify external host name
        - host: authentik.camsab.me
          paths:
              - path: "/"
                pathType: Prefix
postgresql:
    enabled: true
    postgresqlPassword: file:///authentik-creds/postgres_password
redis:
    enabled: true

volumeMounts:
  - name: authentik-creds
    mountPath: /authentik-creds
volumes:
  - name: authentik-creds
    secret:
      secretName: authentik-creds