apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'longhorn'
spec:
  sources:
  - repoURL: 'https://traefik.github.io/charts'
    chart: longhorn
    targetRevision: 1.5.3
    helm:
      valueFiles:
      - $values/apps/longhorn/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn
  project: default