apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'sealed-secrets'
spec:
  sources:
  - repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    chart: sealed-secrets
    targetRevision: 2.17.7
    helm:
      valueFiles:
      - $values/apps/sealed-secrets/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default