apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'nextcloud'
spec:
syncPolicy:
  automated:
    prune: true
  syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'https://nextcloud.github.io/helm/'
    chart: nextcloud
    targetRevision: 4.6.2
    helm:
      valueFiles:
      - $values/apps/nextcloud/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextcloud
  project: default