apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'rook-ceph'
spec:
  sources:
  - repoURL: 'https://charts.rook.io/release'
    chart: rook-ceph
    targetRevision: v1.13.3
  - repoURL: 'https://charts.rook.io/release'
    chart: rook-ceph-cluster
    targetRevision: v1.13.3
    helm:
      valueFiles:
      - $values/apps/rook-ceph/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  - repoURL: https://github.com/camrossi/home-cluster
    path: apps/rook-ceph/extras
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rook-ceph
  project: default