ingress:
  dashboard:
    host:
      name: ceph.sabby.local
      path: "/"
cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
  dashboard:
    enabled: true
    ssl: false
    port: 80
  mgr:
    modules:
      - name: pg_autoscaler # This is already enabled by default, but needs to be here so that we don't override the default behavior.
        enabled: true
      - name: rook # This enables the rook module.
        enabled: true
cephObjectStores: null
toolbox:
  enabled: true
monitoring:
  enabled: true
cephBlockPools:
cephBlockPools:
  - name: ceph-blockpool
    spec:
      failureDomain: host
      replicated:
        size: 3
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: "Immediate"
      parameters:
        imageFormat: "2"
        imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock