apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'vikunja'
spec:
  sources:
  - repoURL: kolaente.dev/vikunja
    chart: vikunja
    targetRevision: 1.0.0
    helm:
      valueFiles:
      - $values/apps/vikunja/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  - repoURL: https://github.com/camrossi/home-cluster
    path: apps/vikunja/extras
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vikunja
  project: default
ignoreDifferences:
  - group: ''
    kind: 'Secret'
    name: vikunja-postgresql
    jsonPointers:
    - /data