---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-credentials
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgBBmrr4Cb3jy6D+Yt9uoI/d4tVeIvdEOafqG1KJUDADDs0syOsMIt+KhCOEUbnVYXQCMAhu+y32jQSBLBWvcYmi2xXpjUNRb/7gpmsRw5NQw8q4pddEAnXWgAMNoZHCe/vtc5Dd25x3ksfhrhumQSo/dGU8mIIdcrLDiqTMBx/LUB5Ggkm9JliYD7aUtjtzxkxHaluyVXcQl3bOPKx5P6Cut/WH+SWb1UY4tu0DhzQ6FHhqR3Wuxpx0OiQVDvMLBrBfvwIAkadwa/YqSGePQUm/z/lfw6VMnWWD9+zvdfYm8+IxOjcIw8JGmUGRYkA9CyWaviTBt8vQjQm0eivjZrSM2ZJr10S4dOG3cTR4S6hhnA8B3xAVUDXIWIuFVhl7tJF3G9Jhs/ouq13I5+S/7JSR6Q7mzADSZ1812Driioy0WDshlBx1ff9It+NR4ghT0j6tjKkBH1aZ5CrccKEkoS9IDmnvg6Eqc/X5WNe3MTPScxkCxtBtFt11y8iIb3MKtSzQI4L7iQtkXNPES0TK5aGgb8z/H2gkY1MsClegWiP+FXaxRttVbS+k6IgI46shgI6vkONFv31bItuMwVsSSmkd0jL6mmR/yWrWTCTvuMeJGUfzCWSnfeC6F3aaffM6HGMhnUXbPwftJo+cQY0Bmu+CUIDTRiCFNwRaMXbqHQZwQUyCyP92POvJ2q38BrquDW36FJVfNPd3oRvenB8r8spSEyDee7fsDq+HbEQWFtg4lr4fTlAvxZSHpkcL3nCSPsWTPg==
    nextcloud-username: AgA42LsO0IbEu0qWGiS4YyUDze8zmwooW97BIWq7Mo+uDASLC4gXwpkgqmhf91FrdonHh+q7yzaTfYX29/oKVjQiEHewI02aCCbQcnEx0knu97eCdv6NsbOnP/28Jd9PE+4iWsEdtqOtnOQv1rnQJ72nwMAAFpzejQPYYRbZk81IgSn3K1qXuxH96VKOSXT6wLyoY9b+GGI/3CWxdwuvWr69jmJV7KwhlJWUh9BKUH8w828g6vGB4cWiegemgEgqtBMbYhxADlV6c3c5x32QUJ9O9aoY9rKmV4XLRDvK6j1x9qhDE5fnxc7jYUq9hc6p7JwUvYFQ5hMozVHh9IrIaMoFmMIENGt3J/5+P4js4FX+TPN2+svWNU+mmUi4m4zCl212IaZ1WKjYrYLNvsyku5HKElHsQxCsLAjjQQBakja2C+5pXblVNaxUQOtXMLwOXINOKy1LkvDbGotvO8fMmtCo6ayCvaRrlb9rYwawWnPEchNAJGnpakLItw0cBgPP9Peb4TdmdR9djzBV1U0M42ZIhnbv3XlGzy6Cl5+tZ22CAVwqV/NJZ2ztl0uHc89Ms9lYp5MwPN1OhARJ1xxXJFDhVCxyinSA4AR8NFCdwpau07rurRYF8BdG3mkrO4H3FdLIFSwfP5bbntLKUwmslcLQT7ioX6aVwROYwaCR2drfhdjYaIlR2E3sQSE70pTTlC6O6Ubq9kTHPTgM5nXuX5eMNfGEAaVcng==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-credentials
      namespace: nextcloud
    type: Opaque
