image:
  repository: ghcr.io/karakeep-app/karakeep
  tag: "0.25.0"

service:
  type: ClusterIP
  port: 3000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
    # - host: chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  volume:
    name: data
    mountPath: /data

################################################################################

#openaiApiKey: abcd1234568

# web environment variable config references:
# https://docs.karakeep.app/configuration/
# https://github.com/karakeep-app/karakeep/blob/main/packages/shared/config.ts

web:
  envFrom:
    - secretRef:
        name: karakeep

# chrome:
#   extraEnv: {}

#ollama:
  # baseURL: http://ollama-service.local
#  inferenceTextModel: mistral
#  inferenceImageModel: llava

meilisearch:
  persistence:
    enabled: true
    annotations:
      helm.sh/resource-policy: keep