apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: navidrome
  name: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: navidrome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: navidrome
    spec:
      containers:
        - image: deluan/navidrome:latest
          name: navidrome
          env:
            - name: ND_MUSICFOLDER
              value: "/music"
            - name: ND_EXTAUTH_TRUSTEDSOURCES
              value: "10.244.0.0/16"
            - name: ND_EXTAUTH_USERHEADER
              value: "X-authentik-username"  
          ports:
            - containerPort: 4533
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: navidrome-data
            - mountPath: /music
              name: music
              subPath: music
      restartPolicy: Always
      volumes:
        - name: navidrome-data
          persistentVolumeClaim:
            claimName: navidrome-data
        - name: music
          persistentVolumeClaim:
            claimName: data

