project: default
source:
  repoURL: ghcr.io/immich-app/immich-charts
  targetRevision: 0.13.*
  helm:
    valueFiles:
      - $values/apps/immich/values.yaml
  chart: immich
destination:
  server: https://kubernetes.default.svc
  namespace: immich
sources:
  - repoURL: ghcr.io/immich-app/immich-charts
    targetRevision: 0.13.*
    helm:
      valueFiles:
        - $values/apps/immich/values.yaml
    chart: immich
  - repoURL: https://github.com/camrossi/home-cluster
    targetRevision: main
    ref: values
  - repoURL: https://github.com/camrossi/home-cluster
    path: apps/immich/extra
    targetRevision: main