apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  labels:
    app.kubernetes.io/instance: home-assistant
spec:
  ingressClassName: traefik
  rules:
  - host: zigbee2mqtt.sabby.local
    http:
      paths:
      - backend:
          service:
            name: zigbee2mqtt
            port:
              name: zigbee2mqtt
        path: /
        pathType: Prefix