---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manyfold
  labels:
    app: manyfold
spec:
  replicas: 1
  strategy:
    type: Recreate
  securityContext:
    runAsNonRoot: true
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
  selector:
    matchLabels:
      app: manyfold
  template:
    metadata:
      labels:
        app: manyfold
        name: manyfold
    spec:
      containers:
      - name: manyfold
        image: lscr.io/linuxserver/manyfold:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Australia/Sydney
        - name: DATABASE_ADAPTER
          value: postgresql
        - name: DATABASE_URL
          value: manyfold-postgresql
        - name: POSTGRES_USER
          value: "manyfold"
        - name: POSTGRES_PASSWORD
          value: "manyfold"
        - name: REDIS_URL
          value: redis://redis:6379
        - name: SECRET_KEY_BASE
          value: ".koDptr8!yx!x.J_zMpUf!vnKFzFsyDxBjb.Bisk"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: manyfold-models
          mountPath: "/libraries"
      volumes:
      - name: manyfold-models
        persistentVolumeClaim:
          claimName: manyfold-models
