---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-models
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn-2-replicas
  resources:
    requests:
      storage: "10Gi"