apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'traefik'
spec:
  sources:
  - repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    targetRevision: v2.10.7
    helm:
      valueFiles:
      - $values/apps/traefik/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default