apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  routes:
  - match: Host(`traefik.sabby.local`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService