apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  labels:
    app.kubernetes.io/instance: home-assistant
spec:
  ingressClassName: traefik
  rules:
  - host: mealie.camsab.me
    http:
      paths:
      - backend:
          service:
            name: mealie
            port:
              number: 443
        path: /
        pathType: Prefix