apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  labels:
    app.kubernetes.io/instance: mealie
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - mealie.camsab.me
    secretName: mealie-ingress-key
  rules:
  - host: mealie.camsab.me
    http:
      paths:
      - backend:
          service:
            name: mealie
            port:
              name: mealie
        path: /
        pathType: Prefix