---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  labels:
    app: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
        name: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v3.3.2
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mealie-oidc-id
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: ALLOW_SIGNUP
          value: "False"
        - name: TZ
          value: "Australia/Sydney"
        - name: MAX_WORKERS
          value: "1"
        - name: WEB_CONCURRENCY
          value: "1"
        - name: DB_ENGINE
          value: "postgres"
        - name: POSTGRES_USER
          value: "mealie"
        - name: POSTGRES_PASSWORD
          value: "mealie"
        - name: POSTGRES_SERVER
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "mealie"
        - name: BASE_URL
          value: https://mealie.camsab.me
        - name: OIDC_AUTH_ENABLED
          value: "True"
        - name: OIDC_AUTO_REDIRECT
          value: "True"
        - name: OIDC_REMEMBER_ME
          value: "True"
        - name: OIDC_SIGNUP_ENABLED
          value: "True"
        - name: OIDC_CONFIGURATION_URL
          value: "https://authentik.camsab.me/application/o/mealie/.well-known/openid-configuration"
        - name: OIDC_ADMIN_GROUP
          value: "Admin"
        volumeMounts:
        - name: mealie-data
          mountPath: "/app/data/"
      volumes:
      - name: mealie-data
        persistentVolumeClaim:
          claimName: mealie-data
