---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mealie-oidc-id
  namespace: default
spec:
  encryptedData:
    OIDC_CLIENT_ID: AgAUvDx+2PzuvqtYY1WvjEE5bXn3NY5afEyrk/QjIbxrhTK+lUlznTM/DGUD6PXHbRk7U4+b0uHY8lQpi+o0y8JVZNmuU0pphf0nUvaVjlui4a1sOiCryAp3GD8QMQxZ+NIWpFB5Jx6OUbijXLVOC3zQTd9lp+J6vJe4VgTo5BuMeRXmdhEE1kpWb2nTfLyuXG5CaEmz2YUOSefTLGCOf0ezzvIaSlOyCTjPUo92H1pUNDhGUvfwoDnGZV0DX9DBduCqEZZEldqGy2bI8CrBbg+aE7/VyNjytpbwicPjsg8JHncXmb5BddJgRQJwL4WQVF65jhE9wUc8aXJAd1igkDMcMMoAqYjMOGWDPUbqUrmSTx/X1kWaTPC726T41I0Q6uI/GAVbU72bJv1o6A0ciFOcrXbsVJCfVSQuZk1BA8ofQODfzKN4vHR8YTaLL0dNytxNqla1+7+RCS37gK15Wo2B5xxsMJvlqVng9wDgy3ZrfdVLSdjlj5BXXXJPwM4PJ8DoPD7L96N7LcA7Jk5ujC/xYuwde8nok9E0QbW88WI1JYT2YNBDttetYAx2rdZnostgpjhKQ/K75nQKzjE3tC6atnwSGLUJd+YNKjuTy6G3OWuqGi+E05C2GSen0ITVpDUs2KcJxHt3/Idz4moMcaJF1rSgTMo6A8fde40m2YPGYZNB5bQgRTiBJf0+XpO2DyfucdPy4n2BlkySUmJZu1rRpTfWyXDbTtzBJcZTCcuZZj274yVT6CdJ
  template:
    metadata:
      creationTimestamp: null
      name: mealie-oidc-id
      namespace: default
