apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'uptime-kuma'
spec:
  sources:
  - repoURL: 'https://helm.irsigler.cloud'
    chart: uptime-kuma
    targetRevision: 2.19.4
    helm:
      valueFiles:
      - $values/apps/uptime-kuma/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime-kuma
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true