ingress:
  enabled: true
  hosts:
    - host: uptime-kuma.camsab.local
      paths:
        - path: /
          pathType: ImplementationSpecific
strategy:
  type: Recreate
volume:
  enabled: true
  accessMode: ReadWriteOnce
  size: 4Gi