controllers:
  main:
    containers:
      trilium:
        image:
          repository: triliumnext/notes
          tag: v0.98.1
          pullPolicy: IfNotPresent
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    size: 20Gi
    retain: true
    accessMode: ReadWriteOnce
    storageClass: longhorn-2-replicas
route:
  main:
    enabled: true
    kind: HTTPRoute
  hostnames:
    - "trillium.camsab.me"