---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
  labels:
    name: pihole
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: pihole-config
    namespace: pihole
data:
    TZ: 'Australia/Sydney'
    DNS1: 8.8.8.8
