---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  annotations:
     io.cilium/lb-ipam-ips: 192.168.0.226
     type: l2
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  annotations:
     io.cilium/lb-ipam-ips: 192.168.0.226
     type: l2
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: pihole-admin
    - name: dns-tcp
      port: 53
      protocol: TCP
