---
apiVersion: v1
kind: Service
metadata:
  name: pihole-1
  labels: 
    type: l2
spec:
  selector:
    app: pihole-1
  type: LoadBalancer
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - port: 80
      targetPort: 80
      name: pihole-admin
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-2
  labels: 
    type: l2
spec:
  selector:
    app: pihole-2
  type: LoadBalancer
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - port: 80
      targetPort: 80
      name: pihole-admin