apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'ocis'
spec:
  sources:
  - repoURL: 'https://github.com/owncloud/ocis-charts.git'
    path: charts/ocis
    targetRevision: main
    helm:
      valueFiles:
      - $values/apps/ocis/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  - repoURL: https://github.com/camrossi/home-cluster
    path: apps/ocis/extras
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ocis
  project: default
  ignoreDifferences:
  - kind: ConfigMap
    jsonPointers:
      - /data/service-account-id
      - /data/application-id
      - /data/storage-uuid