externalDomain: ocis.sabby.local
ingress:
  enabled: true
insecure:
  # disables ssl certificate checking for connections to the openID connect identity provider.
  # Not recommended for production setups, but we don't have valid certificates in minikube
  oidcIdpInsecure: true
  # disables ssl certificate checking for connections to the oCIS http apis.
  # Not recommended for production setups, but we don't have valid certificates in minikube
  ocisHttpApiInsecure: true
image:
  # -- Image repository
  repository: owncloud/ocis
  # -- Image tag. Defaults to the chart's appVersion.
  tag: "4.0.6"
features:
  basicAuthentication: true
  demoUsers: true
services:
  storageusers:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      # -- Size of the persistent volume.
      size: 50Gi
  nats:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      # -- Size of the persistent volume.
      size: 1Gi
  search:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  storageSystem:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
  store:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  thumbnails:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
