disableOpenApiValidation: true
externalDomain: ocis.camsab.me
logging:
  level: "info"
  pretty: true
  color: true
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  tls:
    - secretName: ocis-ingress-key
      hosts:
        - ocis.camsab.me
deploymentStrategy:
  type: Recreate
insecure:
  # disables ssl certificate checking for connections to the openID connect identity provider.
  # Not recommended for production setups, but we don't have valid certificates in minikube
  oidcIdpInsecure: true
  # disables ssl certificate checking for connections to the oCIS http apis.
  # Not recommended for production setups, but we don't have valid certificates in minikube
  ocisHttpApiInsecure: true
image:
  # -- Image repository
  repository: owncloud/ocis
  # -- Image tag. Defaults to the chart's appVersion.
  tag: "7.1.0"
services:
  storageusers:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      # -- Size of the persistent volume.
      size: 50Gi
  nats:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      # -- Size of the persistent volume.
      size: 1Gi
  search:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  storagesystem:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
  #store:
  #  persistence:
  #    enabled: true
  #    accessModes:
  #      - ReadWriteOnce
  #    size: 1Gi
  thumbnails:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  web:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
registry:
  type: nats-js-kv
cache:
  type: nats-js-kv
features:
  externalUserManagement:
    adminUUID: "akadmin"
    enabled: true
    oidc:
      issuerURI: https://authentik.camsab.me/application/o/ocis/
      #webClientID: ymTDwg5sZyWF6QNw0gaS78wjtbfl6lMx0lW8LCjr
      accessTokenVerifyMethod: "none"
      userIDClaim: preferred_username
      userIDClaimAttributeMapping: username
      roleAssignment:
        enabled: true
        # -- The name of the OIDC claim holding the role assignment
        claim: groups
        # -- Configure the mapping for the role assignment
        mapping:
          - role_name: admin
            claim_value: ocisAdmin
          - role_name: spaceadmin
            claim_value: ocisSpaceAdmin
          - role_name: user
            claim_value: ocisUser
          - role_name: guest
            claim_value: ocisGuest

    ldap:
      writeable: false
      uri: ldap://ak-outpost-ldap.authentik.svc.cluster.local
      certTrusted: true
      insecure: true
      bindDN: "cn=ocis,ou=users,dc=ldap,dc=camsab,dc=me"
      useServerUUID: true
      refintEnabled: true
      user:
        objectClass: user
        baseDN: "ou=users,dc=ldap,dc=camsab,dc=me"
        schema:
          id: uid
          userName: cn
        filter: "(memberOf=cn=ocisUser,ou=groups,dc=ldap,dc=camsab,dc=me)"
      group:
        objectClass: ocisGroup
        baseDN: "ou=virtual-groups,dc=ldap,dc=camsab,dc=me"
        schema:
          id: uid
          groupName: cn
secretRefs:
  jwtSecretRef: "jwt-secret"
  ldapSecretRef: "ldap-bind-secrets"
  machineAuthApiKeySecretRef: "machine-auth-api-key"
  storagesystemJwtSecretRef: "storage-system-jwt-secret"
  storagesystemSecretRef: "storage-system"
  thumbnailsSecretRef: "thumbnails-transfer-secret"
  transferSecretSecretRef: "transfer-secret"
  serviceAccountSecretRef: "service-account-secret"

# HTTP settings for oCIS services.
http:
  # CORS settings for oCIS services.
  cors:
    # @schema
    # type: array
    # items:
    #   type: string
    #   required: true
    # @schema
    # -- allow_origins is a list of origins a cross-domain request can be executed from.
    # If the special "*" value is present in the list, all origins will be allowed.
    allow_origins: []
  # CSP settings for oCIS services.
  csp:
    directives:
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- child-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src
      childSrc:
        - "'self'"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- connect-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src
      connectSrc:
        - "'self'"
        # If Uppy Companion is used, you need to add it with your URI:
        # - "https://companion.kube.owncloud.test/"
        # - "wss:///companion.kube.owncloud.test/"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- default-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src
      defaultSrc:
        - "'none'"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- front-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/front-src
      fontSrc:
        - "'self'"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- frame-ancestors directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
      frameAncestors:
        - "'self'"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- frame-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src
      frameSrc:
        - "'self'"
        - "blob:"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- img-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src
      imgSrc:
        - "'self'"
        - "data:"
        - "blob:"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- manifest-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/manifest-src
      manifestSrc:
        - "'self'"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- media-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/media-src
      mediaSrc:
        - "'self'"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- object-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/object-src
      objectSrc:
        - "'self'"
        - "blob:"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- script-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
      scriptSrc:
        - "'self'"
        - "'unsafe-inline'"
      # @schema
      # type: array
      # items:
      #   type: string
      #   required: true
      # @schema
      # -- style-src directive, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src
      styleSrc:
        - "'self'"
        - "'unsafe-inline'"