externalDomain: ocis.sabby.local
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
insecure:
  # disables ssl certificate checking for connections to the openID connect identity provider.
  # Not recommended for production setups, but we don't have valid certificates in minikube
  oidcIdpInsecure: false
  # disables ssl certificate checking for connections to the oCIS http apis.
  # Not recommended for production setups, but we don't have valid certificates in minikube
  ocisHttpApiInsecure: false
image:
  # -- Image repository
  repository: owncloud/ocis
  # -- Image tag. Defaults to the chart's appVersion.
  tag: "4.0.6"
features:
  basicAuthentication: true
  demoUsers: false
services:
  nats:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      # -- Size of the persistent volume.
      size: 1Gi
  search:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  storageSystem:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
  store:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  thumbnails:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  storageUsers:
    storageBackend:
      driver: ocis
    persistence:
      # -- Enables persistence.
      # Needs to be enabled on production installations.
      # If not enabled, pod restarts will lead to data loss.
      # Also scaling this service beyond one instance is not possible if the service instances don't share the same storage.
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 50Gi