externalDomain: ocis.camsab.me
logging:
  level: "info"
  pretty: "true"
  color: "true"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  tls:
    - secretName: ocis-ingress-key
      hosts:
        - ocis.camsab.me
deploymentStrategy:
  type: Recreate    
insecure:
  # disables ssl certificate checking for connections to the openID connect identity provider.
  # Not recommended for production setups, but we don't have valid certificates in minikube
  oidcIdpInsecure: true
  # disables ssl certificate checking for connections to the oCIS http apis.
  # Not recommended for production setups, but we don't have valid certificates in minikube
  ocisHttpApiInsecure: true
image:
  # -- Image repository
  repository: owncloud/ocis
  # -- Image tag. Defaults to the chart's appVersion.
  tag: "5.0.5"
services:
  storageusers:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      # -- Size of the persistent volume.
      size: 50Gi
  nats:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      # -- Size of the persistent volume.
      size: 1Gi
  search:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  storagesystem:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
  store:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  thumbnails:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  web:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
registry:
  type: nats-js-kv
features:
  externalUserManagement:
    adminUUID: "akadmin"
    enabled: true
    oidc:
      issuerURI: https://authentik.camsab.me/application/o/ocis/
      webClientID: ymTDwg5sZyWF6QNw0gaS78wjtbfl6lMx0lW8LCjr
      accessTokenVerifyMethod: "none"
      userIDClaim: preferred_username
      userIDClaimAttributeMapping: username
      roleAssignment:
        enabled: true
        # -- The name of the OIDC claim holding the role assignment
        claim: groups
        # -- Configure the mapping for the role assignment
        mapping:
          - role_name: admin
            claim_value: ocisAdmin
          - role_name: spaceadmin
            claim_value: ocisSpaceAdmin
          - role_name: user
            claim_value: ocisUser
          - role_name: guest
            claim_value: ocisGuest

    ldap:
      writeable: false
      uri: ldap://ak-outpost-ldap.authentik.svc.cluster.local
      certTrusted: true
      insecure: true
      bindDN: "cn=ocis,ou=users,dc=ldap,dc=camsab,dc=me"
      useServerUUID: true
      refintEnabled: true
      user:
        objectClass: user
        baseDN: "ou=users,dc=ldap,dc=camsab,dc=me"
        schema:
          id: uid
          userName: cn
        filter: "(memberOf=cn=ocisUser,ou=groups,dc=ldap,dc=camsab,dc=me)"
      group:
        objectClass: ocisGroup
        baseDN: "ou=virtual-groups,dc=ldap,dc=camsab,dc=me"
        schema:
          id: uid
          groupName: cn
secretRefs:
  jwtSecretRef: "jwt-secret"
  ldapSecretRef: "ldap-bind-secrets"
  machineAuthApiKeySecretRef: "machine-auth-api-key"
  storagesystemJwtSecretRef: "storage-system-jwt-secret"
  storagesystemSecretRef: "storage-system"
  thumbnailsSecretRef: "thumbnails-transfer-secret"
  transferSecretSecretRef: "transfer-secret"
  serviceAccountSecretRef: "service-account-secret"

