---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Australia/Sydney"
  SERVERPORT: "51820"
  SERVERURL: "sabby.zapto.org"
  PEERS: "5"
  PEERDNS: "192.168.0.227"
  ALLOWEDIPS: "0.0.0.0/0"
  INTERNAL_SUBNET: "192.168.1.0"