---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Australia/Sydney"
  SERVERPORT: "51820"
  SERVERURL: "wireguard.sabby"
  PEERS: "5"
  PEERDNS: "pihole.sabby"
  ALLOWEDIPS: "0.0.0.0/0, ::/0"
  INTERNAL_SUBNET: "192.168.0.0"