---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: wireguard
  name: wireguard
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi