---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
  annotations:
      io.cilium/lb-ipam-ips: 192.168.0.228
    labels: 
      type: l2
spec:
  selector:
    app: wireguard
  ports:
    - name: 51820-tcp
      port: 51820
      targetPort: 51820
      protocol: UDP
  type: LoadBalancer
