apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'frigate'
spec:
  sources:
  - repoURL: 'https://blakeblackshear.github.io/blakeshome-charts/'
    chart: frigate
    targetRevision: 7.8.*
    helm:
      valueFiles:
      - $values/apps/frigate/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  #- repoURL: https://github.com/camrossi/home-cluster
  #  path: apps/frigate/extra
  #  targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: home-assistant
  project: default
