config: |
  detectors:
    npu:
      type: teflon_tfl
      device: 0
  record:
    enabled: True
    motion:
      days: 7
    alerts:
      retain:
        days: 30
        mode: motion
    detections:
      retain:
        days: 30
        mode: motion
  mqtt:
    host: "zigbee2mqtt"
    port: 8080
  go2rtc:
    streams:
      office:
        - rtsp://192.168.0.194:554/mjpeg/1
  cameras:
    # Define at least one camera
    office:
      ffmpeg:
        inputs:
          - path:  rtsp://127.0.0.1:8554/office
            roles:
              - detect
              - record
persistence:
  config:
    enabled: true
    size: 100Mi
  media:
    enabled: true
    size: 10Gi
image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: 0.17.1-standard-arm64

securityContext:
  privileged: true
  runAsGroup: 0
  runAsUser: 0
extraVolumes:
  - name: accel
    hostPath:
      path: /dev/accel
  - name: dri
    hostPath:
      path: /dev/dri
  - name: overrides
    persistentVolumeClaim:
      claimName: overrides
extraVolumeMounts:
  - name: accel
    mountPath: /dev/accel
  - name: dri
    mountPath: /dev/dri
  - name: overrides
    mountPath: /usr/lib/teflon/libteflon.so
    subPath: libteflon.so
extraInitContainers:
  - name: overrides
    image: busybox
    command: ['sh', '-c', 'wget -O /usr/lib/teflon/libteflon.so https://github.com/camrossi/home-cluster/raw/refs/heads/main/apps/home-assistant/frigate/extra/libteflon.so']
    volumeMounts:
      - name: overrides
        mountPath: /usr/lib/teflon