config: |
  mqtt:
    host: "zigbee2mqtt"
    port: 8080
  cameras:
    # Define at least one camera
    office:
      ffmpeg:
        inputs:
          - path: rtsp://192.168.0.194:554/mjpeg/1
            roles:
              - detect
persistence:
  config:
    enabled: true
    size: 100Mi
  media:
    enabled: true
    size: 10Gi
