config: |
  record:
    enabled: True
    motion:
      days: 7
    alerts:
      retain:
        days: 30
        mode: motion
    detections:
      retain:
        days: 30
        mode: motion
  mqtt:
    host: "zigbee2mqtt"
    port: 8080
  go2rtc:
    streams:
      office:
        - rtsp://192.168.0.194:554/mjpeg/1
  cameras:
    # Define at least one camera
    office:
      ffmpeg:
        inputs:
          - path:  rtsp://127.0.0.1:8554/office
            roles:
              - detect
              - record
persistence:
  config:
    enabled: true
    size: 100Mi
  media:
    enabled: true
    size: 10Gi
image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: 0.17.1