apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`homeassistant.sabby`)
      priority: 10
      services:
        - name: homeassistant-ui
          port: 80
          scheme: http