apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.sabby`)
      priority: 10
      services:
        - name: homeassistant-ui
          port: 443
          scheme: https
  tls:
    certResolver: default