---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data
spec:
  storageClassName: "nfs-client"
\  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
