---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ddclient-settings
  namespace: kube-system
spec:
  encryptedData:
    ddclient.conf: AgBt0mfXcCsMfln7f/0S+j7TBco6smKewB3hTJqUXg3eAg2vxQWvjCinXcjHn9w2Hy6a7Tcp/i+RfZBE/4+5kRSHgH/g9P7fdknTdHcu9ucFxEIFuydSNTavdZ+b9CDUl7ytoTWvhW4vBcVWg6LiAjHUTXG1pF26vNvUHg/uMbGqaYYZqh5vVfthubpSQ6Xt2hPRt/zm6dJD3NGu4oeqs5+pEtt3Ak2I0EOJxowOrtWFCt3RrEkyRckBrzXkYTR+yv96hOJiChY7aY1xckv43GFzAiFbix49a34lq4Ls0HLV/r6+hfbuSgqfcGsur6asm1KdmAzKFwIIWyIFNXlf2URDSOsCBsR1J9gV6ZcCTKkJpcULFLpHGwQb0axZIUdXulJytBGZAtOiP67a7YrO1xOfIzLDABs/BpYngVgFKE6GoI/XA4anZiWz8cN/2Bk0BCARszrcAnrloSd56Ca26RwwXE1K5I4eU+rPkjKLURDRETC5F8HXLm3N8YyhUW2s4LdfMOmpQrmyd5Ww2+X8N6b5jH68s2w7ifD4chGCsofTGXNQ5z1AsLY8FmmrlogX4usgwVwC39fic9oVSX6tWRhh/zC04jWSqlJ4je8+w/nJEWx5HJsad5WD/hvVFWodf35ZWGR8jlQiBm+YI5kmARo25Qbv5PBJzNucC+0Fv26PCXJMbLlIVYcmr3RNQ4d7an4+pWIIhzeyBrDB/7ZV9ks+cV+e66/4ZMOSly3BcpFKVz77xTkBYHk7krd8hY7RfTAxqh+hCkpcmuKR0V8OXv6kLwyX1BKZghuiHO491UQ3LoOHoYoqya6wKMWkcVsCEM7dei9y6HHTpSm3hqP4uKbTWw5uETLZjoIFD+VtCHib/mVyBQrd4vT4jlnE5Y5SsAd0UqNFrCCT8EXwuSrryPos5jF0B7J+ej+g4UkGn6A97xu8ZwsA0Y5gSKToXZ2YWGrk17C2V/qdnbxTOu84s/e2irw8sSaNLqp51Y0BSo9QwcWTkB+DSjFHdvoxYyVeJUCtdZNNgldXxhBTAWPi5Aw6k1LRZIPWXMiSbP21VUJ78G1P8JHmNM7fSjAgyyDCE2caolXs9F43YiEn7Rc3yRiAQkMQSQ2hdlYO4fEJSHeR8ySP+jbYR7Qkf6PQCcvZ0x5fZsHp3WXtxqEQs4AYFbwvY1oxdkN9HQcFVB6TI6LOeA2yWjDJIXWI9YHevOvpxQdpfN7MTKm9uBlOWswNtrF8nXUJcA745CRE+DiQOcqkBCAJGg9cyd/6ssJcrmmOwaONqXSdaoh2guxNSU+kNZ7Jf61yjzabXL8Lf+4WIIhsptHNWA==
  template:
    metadata:
      name: ddclient-settings
      namespace: kube-system
    type: Opaque
