---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-settings
  namespace: kube-system
spec:
  encryptedData:
    ddclient.conf: AgAUu9AKAf5Spt15GupJCZiSwAfvttKHDi8E+gvhw9/cF3Bo6d+R+AiRU8JRJLxM4GxuUztxr5JjHlyE47KodZ/zmP+MN0irK90OarE+HXok0xCFViTOOUfYhU6z6aOT2KY17kpAeoQCKHmrH92ZTUH9Y5wx0/NVdCuU0QCm+gVmGr4zhN6lvDSm8uwvqH+nzvA6mD1cdaJaVCBduRGbV6JAsLj34USm74Mfyk+6T7WAtpOT7AwoMGWZCx6TUhB/v8Yfyj0AEEOJSs3D3ATYUGnCxjasTV3++uK+9QR0LmIRwkYgxzwUynWpqC/cA/NanWrGsOgUzcspVvhZmF7r++gW8jQNoXPVzM9PA9ymaKi9JAeoYG1tLA1TNIzeeepbo39LU+jUVZREGp2DekTJpJLVBkBk69fE3XtgcJai6G6u4XKdASg2r+DdD36mJtBxShwXrz+qilGA7ZwTdoMRDlX9Hkgt3Dd7ZtGlr0OpL5ZAZ04G1bM95f/mfGCeNOM6xBawf8jL97eLLD/GUbiSc8EZCKIN/QJIzvvk7WX+jAUphQqZLGXfYSaNQK2An32IqZXZtpuPWVf58FPx5Kv2lQJWtbkBXnNQpQjL0mPl1hRxHr9J+6TYrCK3W24/ATJAYhHZcBnVYKAsmtUxTlph7fIJKE8PGTBZQEtlKS8bQ337j4fy6CxDwLTTeMj4ly8x2+3TvFKkxl2hqe6Jpsf1sHOCIFm5IH3tLR+CyXuWJWu6tKyT6v6KnQZVaxGfmOjcbWybqJvaNRWFHO42infOmUHDecN0gkOf99fDi3aBFDDitNpLyi/RZnSkTuH4Yt+KfD6CLHg90pCrBbRbPKjGEhL8I+CSXeDUx7LKM2Q5dH0UZcYmVwzm/0PjP6AJoXwUBobdH0TDLngJblzBGdynWKT56lXiu9kt0rQjchFmXSe9Lph4TjqvVWSQf5p4T+7HKMZGsSyhdZAz8Pc3Zy8tmQiP8/2zz4HFx+OQZ8nZOirX4TD2RNtfPZuzu0/EpQrHwQ3DUW6X4oE856Iv2ao/HyCG2kx/SEiACAcqcuyRcusSRWktEcNY29rgkVvEXdu1/3VLSelmvUJkR/IWAB4WUvBkQl7/2AYAQZr61BLSctYrQArgtOdfc8lkiFo1lq24ha1R3hAXwKmn9SBQZBuGu4tUepXm4PL1Snfhi5wluDoIJTof2DaJspZebBnhFIPn3HrBbHDtuBBFvmetg9pqNlQwEYxJip8WlUlOnwrxrQ==
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-settings
      namespace: kube-system
