---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-settings
  namespace: default
spec:
  encryptedData:
    ddclient.conf: AgAEF1Jn9BCQWJ2//Zp8L0eDT4STvfgcModAbXuCC9yb/u9Rpz9Ji9esCLmMdi9IefJeLRZH2AFrOC7MkwRVd0k0HOWMm9ehXoCNe52yCToIdsYOePlnb6mbB6hdIwG1gA386tzugoQ0fGHZfdQhM52U/9hopxChn8GndIridr0ENIM/nGgOqSVlIRUMxZSdGX2qJiiEdgsN80JHNwgFn8k1lZEGK4AdhnItgS5XmlEeGbeVnkNnqgoogpq9R4EFXtPWEeEAwUPkN0KQ4TCCHwD/K//bO+tC0UiE5qz/jrSkBr0CPzxUhllfxVSP7bUEiWkRj8MnQpHCGq0TtxOOUhxDB0bCX0nqoYJNxr6H+uUV+QUy2hMP833LqmIrGSgeoSolhJBqGSbH09InLbC0Y4GwmdUSIPlc/IX4/yi7M/+Dw3MmAJW29Oyhv129sF/N0HSd90ReU5xj2mpx2/bIbgzc1wg/JUvVYG/1XQb0SRzDC01I92LeH4tdSeIFCG/PQUPBM92uwZequz4Sy8iR3BJabVHBE7YmYyzAOrFeQ+4fwoQd0CEuy6LQ9VvBa3mDXbQ+0g3X3JATpr7tV+J+uIngew96rKnaUJeJYWFToGPPTvi/Gt0tS1oumqMiEvUoxcFlePT6oxC5fzUy5GE3gA45QMMkk9UrJZfyqsFqdI73NDzqoElRk4rg+4J0wPQVxSAsIbCvwRaf7K2IXagKf7Xxx3x2YWb/gUlQE9z3zbsjQIwHN82MdGbmM3Jz9qxkZ6i81zfdL3u/BqhgqwzoaYISxEZk+xInjT+FY9tktLz0gH9FzlOoVanu62ZNe5DaAF1cBSu/dQs5v4IJtko21bYxhABpALHEfltcEXu5ixt2Q+yQ/2c0EL0QGlZe384pt0BdIChd6EIHeUzK5N5dg3dbkhWbSj995iZ5KZtxsixYi9V7Yq2eY6dHzvGj5nYEjEjdwxSyu/uMuf9q8FgtMa83ADB6WRA7DgByl76i11rM8lJKBS+/iz6fdHhXjMBkDfCJPuImAoS5piuf45mVxLHRdPsAV5KUYNu1OA5XY8tmxB5w9RNv3q7LC3s2gcsPxUtvdfg9+bT3Fue0+koODr/8I2G5EgbP9YqFiC7c96Tf41o=
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-settings
      namespace: default
