---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-settings
  namespace: kube-system
spec:
  encryptedData:
    ddclient.conf: AgBsUZJxzO69F2S/60o2/Q4hp8jAOuv1Zq9BPWZYGJI2hH6IUw1Ltajzqud8vXMS4jJkeQhEWPtarUHDQY9MOd+PdwZBoZr/5ahDtj2PpWBXYYM8tlHnVwEAsD3te/zbsTHWh4WFTzpAyo0LuhHyHa0nH3IPVw1ZVg5GznMgAnMYGiP1hy+QaueANHbA+Ik9IvmPCkvK0yWJ1ye6aSdJZVoWhIVkvMEIew+LoyhQndIJIWvNoKLWZpGfzc2dCXRteFcUraEx+/qIysL30sIcZ99Gstqu7XbxviFRNIvIsSq5Aviim20+uKEB+dhGqAl3++2gYG/+YTahS30FiBZ9ncw6A5aTvIvhllZockyloH0uOCMKLQ6AJmR5FOOhCY+g+QR+e9/EZ9mBzpWY7qfUg5/Dugv/Q/K47xPwJ76SUqmVeCeEvUVUQ2A/3tlFQCtUPTi+y/R84HytjuSE5+9sA+Cvo6p7kF169LJYtlklYvmzgqJaoYvkVdRA4Nw3XyA3576NPWJmkdRiSmHksfmaST6+QwK8TUgoFEpqTqqtySxcMwDSvELCDHFSZn4efKmw8+jQ8snRmd78G8AXYElbwFV+XzUqL3embk0SMPGwsYEQ5TlHi1RLmpttXMSZ3txXGlQk5kRMdy2MVXe1/kLWXKpSNw4Slxo/F0mKP/SEBVC5xfXXNcYQ/RQ/nAQ0bUaaF9qSc+lJ2pzsmg61ST3x8zhJLDBY88JjAZM7/CAI1PQRJRaNk9+fJImCy9t60bc1tS3wbs6IVAnblqw0/r9mjllfw14b3YjBi+t01+ZCPDOW5R3EZJE1VobFQ/EVNPXWF6Q6dPWLCmsWwRPYcTzxAHl2+ZZhiZ7oUtd/V1v7wTDxqFRhHmB+AU0OMVhW5xR4n5AaRb9j+wFBcRSE9aN84hW3Mgzeswv5BEESxkc1qlICJZnJ9rlEqaOLPTtCvNuCtZJE3RTP5xpwol5PpsuyAd4m333wLPi/RBbXS7ddCC/GsgdOLYcpsVsG6E5ZOC2PFkP5YaGFc5q6GC+n8KKlvIeT1OAU4M0Eky40zUaCFeKHJUU+XlRERHMlOaAKcms5Y4VPBNSkURab3tndPvjeNinedQhg+aX3I5cDlcJsGA8lMAvTkbo7+jrBui3Wgn6JMuimfNb7ozAu/FnLwVJrYEaN+Q3Kw5/3hJz8o/FF9QHgrY9fZ7fJ9zO8Y7/LfeGMUyYMbjMVoe998E8OWuWSruhWutlgMevJ9OWl2nUp5V8ZOd51uFmSeop2l8X/tZiI6JOnMhNkjSv1fR4D4FLi7g==
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-settings
      namespace: kube-system
    type: Opaque
