---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-settings
  namespace: default
spec:
  encryptedData:
    ddclient.conf: AgAfr8Famzr6fgBfFRQd2woDOIjNJ2246YMKQViulGmKWDX1x7LGMXwX7J4sR3hDHn0Z5RRS7YXvwk2yJmZ56Tvt6qChKVpkx0epB32ySNCjuP+ww3q8GFSaktSqvxiwHpAWTU8OHkO13h0Ed9gNSQJRtWbhqa8baPETZCnyYzFogAP3ZMhJsoqDwWx8p0kbn5fcdE3rJ7Mv+xCFtf6nZ9TdUfOXVLLy77H17F7CWGD18lKYX5ZWDSJfIOrcc/yfHkFPXd5i4nkFIayvdv2Mu34KZgrpU8LWbHd8PqBPPdw1yjHTXe4X02CNVGxLFB9imZJglxPgXVSkGqPy0Nxnd/X+QhY2sk0sJfR+QFvXCeGe8H4TxUaYjRD0YqbRo0uLpiloHme24JxdPWX1VyA23sim24grtRVFFH2lKMEBtxh+WwFaOobNN1kgloG5ZcRaQFFPNfradVJsFRi+At/W85WT//udip68L2AxzW2ZR1jAebWdnxTUIckIoHDj19F0jPp2CRCDBpm2pjFrfCX68YTkh5B+rs3NdCAc1v0qQsBmj67KO0GwUiwpe6Wd7Mjsu2iE1MuZX/7RbrcresuHYR56y6r7unNB93Vu/fNE1uDqRRV0/4pRRgsIdOAK63A9RgGcNCUZaG2sFCc93kFg6ww/iaGW5s8gvAOTVUnpFCiWH/Q+eea50xy0uf4zsJ9j4UwHITZq8nDHhQo/RV47gkD9UUL8mJ4/jUjPzytDrMqlcHjkG+KbdYfFgylAfaqU7yr21EC4SZrneoP04/w21s/mEGiw26TU/WvG+EyP2AS7UkujJlcr/KOKwqAw/nkHinRIET+8HovboeQTmoB2KUTTiDyQy1W+JCHZ0/K0aCsrifcKeQOCqOFlv49cnPJZtPLP0T3bllDlkfTt4Qn0l8rkBuVLYs9PfUWZVUxEHCcl80gzrFeLp4QQtxcRJ4xf6Xu0IQGE1TAwa7ABlnk1tBgDyCunIdLFPG7F478YLFTk50xHYJ7oT6ZZACmJ33J/qtdzIFhL3l7j1oI8LuEiZvyeqanUcm+2Lr7OXQeXXs5HYdUAFvx+aO1r+sihLDtlpUBgme77P9zaTpfnPL9mCJeeFVKZ+GDGxKTkFRiN7e2qZ18J2w==
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-settings
      namespace: default
