---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-settings
  namespace: kube-system
spec:
  encryptedData:
    ddclient.conf: AgChFO0Rx4VqWTIJMIO4p9HyNpcAP1mbSGhBF6bur24RRO/b0pX2miRrX1u1R475kg3iwWjVaaXee2Fe8YRsem4HQUZ3DoZsH0crSeVah3Fngc7dPj8BTxKW7fMyiX+VZyu+5tasehlswOLGd6Hq7BGChsd3UWtCdYd4A8cLsDDgmFT4CBidsdcQtMUJUtr9EjCz/DRUHli87d+HT5weQm3cFQxeE5ucbVcc5gpEwqN1gTwuuulwv3Iqum3htneJJ58ma/1aKwetJUi7ZZ93iTu9Jx0/Kv5MTDApX9V42/9Y5k/+fpV+AK2+xPV2nqZ55qDpcGz0MiH0NXP7s9qLWy9NKBly/KMj0ULbKmJFsDU1IVE9M1981R+C0HGbJhkB8jxjWBgzJwCDXEqv9FKE8nS2A0mQObK6KvuQoCyLNaNPTyfHxRv15jZveBiyv/W2etiSuDjo+q2I6ujDT550rqsQelWgRQXcBSu5HJ2+n9jZCQtdtGmR2wAfbNYc7weBU+ICyQBuLvwNRyC40jwQBIS1ut5Yh+mcTn4WcjGvyRBRPhSH3JRjiWnrebbAi5JkA2kxxI/zwiYJcIY0Mw4kys+OT9cTkgh2571tG/IZWI1aFKM1TN4/02AnJgn11+wp0sGCBrzUAJt0/Fowl2etQI3NnEu6GGtzSrY2TyMw0jK1t2GrR3Dyhe6/lY+QdaK1RK+RC4wh8tbrtEuGNqS0Mvzi0lGcp3elS1mCSf68ZBifXuYOObBOqQQRF9MISUZLFl2YI+U/vutfivZtyavk1fffMbrWrtaLDZwmFZBUlHOHW2SXSOcTvGcToPGCbSdfvacvUFAKnjrSPHoEryn7LpZ6x7aBxk6dLdqUxkVjhVC/r9YsJvEnxG4yAdAmeiIxATWjz0dB1VOgZSfxxKpmJoIkOxU1gxdgY1yz+xOSMjlocorOpw1s6LT1XipuZ4ZiqW+NmtQ+CyqfBtZBHPOqtUMbBXpo1odDK2jdHqlvyWkdo91sYZh5DoTcJGN6p82rmK9jGeCkD8LNFppYkhpK6TCJov9PYTiOl69iJZuGM0ufLJi3PPgOCF31Rjwd+beAG0tFdtlxWhudVMQImtN4UlOniko6LQQUtzhwY6zVfNg8MESvIsm9F4IPMlztL2x6vOq1Wvi1PTe5D6razG2pe+ACY+kJUMKQIg==
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-settings
      namespace: kube-system
    type: Opaque
