---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-settings
  namespace: kube-system
spec:
  encryptedData:
    ddclient.conf: AgAe/0TffYbsksAkfluTJR3QdAYvanokEhznzUSswVazDZj7bj/HsfJrJR/PPWcWRy3d3A42YSinz3u7Tnfvvs/IvqNzf3o9dbtW56my3aRjvFnmhB2w1KRgk+/VHUEmIhKYUJOy5i8YzhpERK7L3LSsLBLHnDXxXIq/h+dwkJIE0F4wcDOStMLat04cOombVE3c7LSHsO4whXrk5/xm3o/VCz2MtZc+yzJ48U2+Xc+WPCMwrjrDwNAMgPF46KODbdhPdFd1u+dN3PnG0XjDqK9gGg3QZr4o0CEFHSPXSj/lXG8ofkMHq0arn08Dy8IQq0Dkt8vmDP7Hwsndi0dc2bXfRbQzygGB3mZIWsj683gPbsjhIvlbgEAqhhFR5eXDGzPOxmmGSynxu2AkIKVc4VYdZNsOIv6FnD8Dg696zCCSIZ/xFvB3jOYAycsKZOf8lJ9kP6jnc/YEQ/UexGeDPiYNeRPfWjbutMHEQ8Z2sPSgRm3bEp3HtRDo8manLvPeq+iu1AW1qGtfQTjqMqml416DqCMZ0+m8ajzXqTbGbYNmkovlSrviEukzC40I0QLr1CExNhQCUInqckEdmONmun1qg8j8JuXqLAqvSegvA9G359PQ8rDaDHuyUuzuueC6Lwf08XmcJXKUQKenB+IWk9ERymNzHaN7dc+uiwzownMPdytzsn4/M3AF4Sbs9Dvaja/CRKHnrsy9p7sM9KFnpBsdNsibVBXEXi0NWepEvUTheLZsGtUPIpxVUoKG5df5grzbrCrQPmhFLDtzXhAnGL2q/ynlyawOUyfpcAEnI1og7QwWfBCaSGEhQQSuBA4CSqSHCNGYgvjKEWRKKPqEfcd2+jY+F1aOjuwsdaw/ArkLTQvdCAIKweTr9yutcbORzKuHW2aKAFtb7na0q5P3CX0a/QUePj6ajFQu4gUyX5mIV/Bw0rk0YSjloxt0niR5eVS16B1nySc3qDIJHMpyXqjY0Tyea7LQCKVNlf3yHQP7JzV6CW7Cjr5KWHA5jRgR1olbA9oTwNO+7lOJo3uPgSM3lHNhWNJxfzrxVgo7iXljwbgJ9yitGNJo+k05YzWMGeYA7ddAz6uA9TQdEuuAg+MMDVDdQ4TQQEoSWHO84aLcckatHVV6ZBUBPAlR6yd0V0soB4ONAfBw2UDKEaMkuaD/VJJt5rAtDogFG71o6OjmGLQoCyhbaIXc5VJ29fLRTml0i05I02q5xfreRp+CuxSPvFW1h2h36T2VY3OK3DlOtXfzopsGb0FRwKNyJCF4JBD93jzCiaNjCjzDLHfAMgg=
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-settings
      namespace: kube-system
