---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ddclient-settings
  namespace: kube-system
spec:
  encryptedData:
    ddclient.conf: AgCiclAKdTC995bTIaGwoMjU/YDiVuppb0SsAp6UNUSPv0seXrHcW1ivPMGt5pLDV4wNweKG1yaqSqE1UWljS4VVPMH6WhqkRCQ2aCT13yQFq7Pd2qGChG2Q5Z3iJcUK6yoWip63aMECkFhGDTITk8PexrnPqnAkorE4BcAoXWqdAI0BFrNHTZSFD8vM44A19q2UOyoC8ig2T3NocN2a2KYuyjWVGENHieYe8MjxaS18g4ticCr2C4vBJUyAYYB1CSvjNKR5N8khZFApFqjlsuNBZmX+mgP6+uN0WTDYK4NRUD6bVSwlSh6UZEnDAkQCG7G2AWBPdHQkWRSh04vIpVV0NY+Sg6vEX1+YF1nSZly3XomK1aksSDIR72dIAAfbwTDj1VSPzvyxrn0U3HGEGO+fr50KqeMwK2N0XauYlGwobtYwbeFdPXfxKhbFcRl2xhqMlv8Uf6WrmNcO1ts2gOzoaPR3ulD5kG8sS2wTXqTTLXJ2s3mQdNARDD2s/heauEQV/S/GNyKbRvZ91QOV1IOMRuMGHpLhLJdmmgBnmOKj7zQ9kfJVNEUQiUje6AOIXiyAwIKIywThc8omGG72aqkLh3q9ufOEMHueh8DoDqzI1aI0OQbrx7j18z1BuB7JCo2LwXU14lhRJvfOtyTYxfcnb55e5R9i+9HmMKDJv50gG9cbY9TzjHMZhJzgYOJjZZ1EKDPSR18KOoW+nVxkjLAfi7IgnTC8KDtGUZtAlWCi0vcY3CT8hp7lybKaAl3Q+C6/Y0KSe0YUJEgtbVw/ZEXLDC2DOjqhNul5PCpS19XW5NQTSa+imkgEPwCGkj+igyO6lbYQ6Fs2oqpRi75i+uOOlNu5m39azgkR2mOqYic8YEa3qFx/bWgMHvTy8XuhDHhWrSBfdRQyOS4E5uMtwainPz+1Aqe9I35ZfSZCEi8w/Vr4ycHy3Uu5Asg5flkSmF5+804WuSU9C7dgmex70X9ZIs9XnUHrbWSVmXJsbIxNajra1bSjfg7f3QJE9YsD9POgBD0CF91MTAlzXtwQGLGsArkH80ynx5kzjJD+OUrTukDCzmFVBbIRrEgB+e7x7MzCjQNqGTRyls4mk3KkLXdp4oVCCGmu3u0DqWIIGyzrVPMvx1adiFFkBP8RyCmR0zgJJpzacbJHeW8DQOFrGMj8S3z0kXRIpMTsWpOjJptKO2KHrfpw71Q/WLdmE9tdvyeJd4GqF1DGS5yn4Dvs3rkQV8wvHowQ6bI673o5J7wH6onm4AUfK2V8Q2Mc4G8eihKAQoHAumlTO2+f4oP8D+OPoeH64J83E8uejsx1bVWMWT88x/i0mZWuuJKxMFx982YYSgyN74P/1SBh5w==
  template:
    metadata:
      name: ddclient-settings
      namespace: kube-system
    type: Opaque
