apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: ocis
 namespace: ocis
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: ocis-ingress-key
   solvers:
     - dns01:
         cloudflare:
           apiTokenSecretRef:
             name: cloudflare-api-token-secret
             key: api-token