---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldap-bind-secrets
  namespace: ocis
spec:
  encryptedData:
    reva-ldap-bind-password: AgBTujKFqhj8eT6Y+wbcOqCQwbV6XLGvjVjXSDcrFJSWhkME5ChSNomPnt7QJcqOkHkALJnBlSz8P/K0FjfF+sMLtuJEQkXfrec0HNg3CZ3LekMyUB2gt9qhwsZh5hRGv9cyFi/IiQ/w4ZwQ7stjKQRSRgVnKtbbPPLdVLALQbTBZtytGs2nOmFVwH2la9Cpm+Qv6Szt5NErJOk7IHISQtYKvrpSHnTClIwxXawZ9ZrgY7NT1+PWBgQzIjxV6JTsIV0mYCU/ZcoSeMHwd+cWv6pRH7WsLgMvl4l0uEbUc+xPygImm1E5mNbhZNIWqZ9hBCjWaZWFLQZSe+UEyIZNyUZSqsQjZkFa9Qg9kgkJe+VQuPvliQuJ65ANGMawmV5yQNeGEgbZab6irVzcmBwx+jc3dUW9WKbBXTAss2w6VELz2JTezhhaVJU0zDAW/CVLwrhH1VzoDKwNXGvO5unoXFIUkgWxGwUWGwlDRri4kUwUZFBAphobrAXprP9QFgcl6hKKfejWQWZrPZo2biQfKFvzDoPQ2+53ypMP21d5Z4oY/Fh1wwo9fHZdQ/C8LAbTWSKKuHxDlt1O/e09RtJLMuDqN4AgRSpng93F6tTpwDKyJrtsv3kVie4B5be5K7GkirGhvRK+o3H4PoJMY5QBDbqdcTu3jXoJ+sODOzu8fXXQqpAWjfTEYwUghl2x1OsX25uItrYRZSvyU/9aWViUdNs9L86loFOzWu6GXLN+sNAoG3Dz5j/5VjJY26fWTAjRADfPtg==
  template:
    metadata:
      creationTimestamp: null
      name: ldap-bind-secrets
      namespace: ocis
    type: Opaque
