---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-typesense-data
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"