---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-data-backup
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-data-backup
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storagesystem-data-backup
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storageusers-data-backup
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "50Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thumbnails-data-backup
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-data-backup
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"