---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-stack-grafana-backup
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-prometheus-backup
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: "10Gi"
