
apiVersion: v1
kind: Secret
metadata:
  name: ddclient-settings
  namespace: kube-system
data:
  ddclient.conf: ZGFlbW9uPTYwMCAgIyBjaGVjayBldmVyeSAzMDAgc2Vjb25kcwpzc2w9eWVzICAgICAjIHVzZSBzc2wtc3VwcG9ydAp1c2U9d2ViICAgICAjIGFjcXVpcmUgY3VycmVudCBJUCBhZGRyZXNzIHZpYSB3ZWIgVVJMCndlYj1keW5hbWljZG5zLnBhcmsteW91ci1kb21haW4uY29tL2dldGlwCiMjCiMjIENsb3VkZmxhcmUKcHJvdG9jb2w9Y2xvdWRmbGFyZSwgXAp6b25lPWNhbXNhYi5tZSwgXAp0dGw9MSwgXApsb2dpbj10b2tlbiwgXApwYXNzd29yZD1tNVItMHdEUlhEUVl5NEFZZnkxX20tMkk2UDRxQXBJZHBCS0IwdV9XIFwKYXV0aGVudGlrLmNhbXNhYi5tZSxpbW1pY2guY2Ftc2FiLm1lLGplbGx5ZmluLmNhbXNhYi5tZSxtZWFsaWUuY2Ftc2FiLm1lLG9jaXMuY2Ftc2FiLm1lLHNwbGlpdC5jYW1zYWIubWUsdmlrdW5qYS5jYW1zYWIubWUsd2VidG9wLmNhbXNhYi5tZSxjYW1zYWIubWU9

