
apiVersion: v1
kind: Secret
metadata:
  name: ddclient-settings
  namespace: kube-system
data:
  ddclient.conf: <base64 encoded string>

daemon=600  # check every 300 seconds
ssl=yes     # use ssl-support
use=web     # acquire current IP address via web URL
web=dynamicdns.park-your-domain.com/getip
##
## Cloudflare
protocol=cloudflare, \
zone=camsab.me, \
ttl=1, \
login=token, \
password=<> \
authentik.camsab.me,immich.camsab.me,jellyfin.camsab.me,mealie.camsab.me,ocis.camsab.me,spliit.camsab.me,vikunja.camsab.me,webtop.camsab.me,camsab.me=