apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'matrix'
spec:
  sources:
  - repoURL: 'https://camrossi.github.io/matrix-chart'
    chart: matrix
    targetRevision: 0.2.3
    helm:
      valueFiles:
      - $values/apps/matrix/values.yaml
  - repoURL: 'https://github.com/camrossi/home-cluster'
    targetRevision: main
    ref: values
  #- repoURL: https://github.com/camrossi/home-cluster
  #  path: apps/matrix/extra
  #  targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: matrix
  project: default