certManager:
  clusterIssuer: letsencrypt-staging

serverName: ftwr.camsab.me

networking:
  ## Whether components should attempt to bind IPv4 (ipv4) /IPv6 (ipv6) / both (dual-stack)
  ipFamily: ipv4


matrixRTC:
  enabled: true
  ingress:
    host: mrtc-ftwr.camsab.me

    ## Disable TLS configuration by setting it to false
    tlsEnabled: true
    tlsSecret: mrtc

elementAdmin:
  enabled: true
  ## How this ingress should be constructed
  ingress:
    host: admin-ftwr.camsab.me
    tlsEnabled: true
    tlsSecret: admin

elementWeb:
  enabled: true
  ingress:
    host: chat-ftwr.camsab.me

    ## Disable TLS configuration by setting it to false
    tlsEnabled: true
    tlsSecret: chat

hookshot:
  enabled: false

matrixAuthenticationService:
  enabled: true
  ingress:
    host: account-ftwr.camsab.me

    tlsEnabled: true
    tlsSecret: account
  additional:
    auth:
      configSecret: additional-configs
      configSecretKey: auth

postgres:
  enabled: true

synapse:
  enabled: true
  additional:
     0-customConfig:
       config: |
         retention:
          enabled: true
          default_policy:
            min_lifetime: 1d
            max_lifetime: 1y
          allowed_lifetime_min: 1d
          allowed_lifetime_max: 1y
          purge_jobs:
          - longest_max_lifetime: 3d
            interval: 12h
          - shortest_max_lifetime: 3d
            interval: 1d

  ingress:
    host: matrix-ftwr.camsab.me

    ## Disable TLS configuration by setting it to false
    tlsEnabled: true
    tlsSecret: matrix