---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-config
  namespace: vikunja
spec:
  encryptedData:
    config.yml: AgBntXV6w+B/ztJe/xRXUJu2pQoQZWiQmU7bHE/i+bI4EdZxqs90bqXNGg9BFBFKNO5Ll0Uo6WI0w3gwZv26H59ZJBJclVf01rmnjwnkTAmmpuQsVxq4eyxRTA2I9T68KSvZJgoBOA3+zgUcmHTvlNu9lrySj7eU4+uOCgxdpBW/7E3whcnPkSHzeK62iaumozcpQvEJuts1XUXjJ6ZkR0kAA+V9dNNm5pA36wqGWh8Afan1CkutKKNtM5YwECWzjm267XCsiNSiJu+xfpbOu19VJZe+84qtdu5xKN36QWtJnT/jmASXtl/Zhqe29NpJ9ML/ndSReWG3n0XyhWGiWRvsjAE4Cx35+FkJ7TlXo7+Suv5noC4a6cNjamAb5Vem+Xuby+2f1HrwqEzkayk2PiPsJ0g8smrRRnn2HdsDVcPtx1Ln6zVZfZf4nF6LrKApuULUdhysZcVL7Gv7ZoXJZ34rCF6vK3vNGEXmbCKUXiHY4ROlT8foukaHdgTek6omgpR3/GsOvLhWoDlBSsl23lONx9gYpJGyIGzyCXX7M7AmGaW1G5yVH6tcLCXhKwUV6hAGfm/qY14xxUyGrDb1/JK2OhjsJR/bsgHHxmr4TYYYuE5Kk1wUY3IVP/dcDhTMw9p5O6E8hawWyqSLCvKfcUmu2pwbr8FJGgHSmgdA97z/fcZhsQF00tPy6MdC02cxhsThVAdyXWm52yLpFl+KRMui4m8AGAWEe9pBQM47+HApln+kmDO8oO/brTKG0ivu5FZKrK+eUOKO3gjtdQo2fZ8t8vYF+nrUGz4pfD88u/lCTCWrg2cr9Pge9mKE6BOimg9Me0/zS+CpdIr3j+K32ooZ9v1lgpm7msjLwIQfF4fM6AiLHoMuzCm9vhBfeU7P/dVA0LjUAYxFkVIvOK93DLB8yPCVDrElen9izfl8lP6zwtDvPO50Z9j2SWezk1AgfmXfrkjpVZ0OROBl0s2QvMqGXJYMrmi749gOh94z0OE2DcdCR0ZRec7BP09oj+FNEeAh5BA/kO1mjCLe4WUDWBO/dkC52iUIlrCHFJ+lOhpORIdglE/nHawHH5/jEiG8tcZmMA2PfGb8yc9X2s4S0/gEVTwPV1dhQR+aLfX+LIeSTarFtyhx9+p5qutEOxtSnnZ48N4UA00sEB8Uu5Ebu3ySvyn6xEZf1dr0PQrrSv3GO2FhiqLa7OpBv5Opyj4uShedyndaCsuxJE27K1tZ1o5GELaixR8sPPQx4DodHOGF4Qf6BB8aBNXhBrfEO7575VkmjyOidHpCgY8/lfE2n346fYdOxLPJU5wt+xXYhECBm4tdtd5/C/FXDeRHVcmCQ56wVKO/qzYrYXYM4mbP5E1XKtf2iCRbp8aZvV3h9Z++hdzgcSuC1xyUkADhxxYtmZrLjrPXzw1v4WnV+NRmGjkKjEYQngP1YKAGwxgM9+flOaYiJxVT+0gOdg==
  template:
    metadata:
      creationTimestamp: null
      name: api-config
      namespace: vikunja
    type: Opaque
